server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true

logging:
  config: classpath:logback-spring.xml