server:
  port: 8080
spring:
  datasource:
    member:
      jdbc-url: jdbc:mysql://localhost:3306/member
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    order:
      jdbc-url: jdbc:mysql://localhost:3306/order
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver


